window.defineEntries = function (addEntry) {
	yr = "2022a";
	codeset = "us";
	addEntry("al", 0, "Alabama", "Ni/Co", "The Difference");
	addEntry("ak", 0, "Alaska", "Jewel", "The Story");
	addEntry("as", 0, "American Samoa", "Tenelle", "Full Circle");
	addEntry("az", 0, "Arizona", "Las Marías", "De la finikera");
	addEntry("ar", 0, "Arkansas", "Kelsey Lamb", "Never Like This");
	addEntry("ca", 0, "California", "Sweet Taboo", "Keys to the Kingdom");
	addEntry("co", 0, "Colorado", "Riker Lynch", "Feel the Love");
	addEntry("ct", 0, "Connecticut", "Michael Bolton", "Beautiful World");
	addEntry("de", 0, "Delaware", "Nitro Nitra", "Train");
	addEntry("fl", 0, "Florida", "Ale Zabala", "Flirt");
	addEntry("ga", 0, "Georgia", "Stela Cole", "DIY");
	addEntry("gu", 0, "Guam", "Jason J.", "Midnight");
	addEntry("hi", 0, "Hawaii", "Bronson Varde", "4 You");
	addEntry("id", 0, "Idaho", "Andrew Sheppard", "Steady Machine");
	addEntry("il", 0, "Illinois", "Justin Jesso", "Lifeline");
	addEntry("in", 0, "Indiana", "UG skywalkin feat. Maxie", "Love in My City");
	addEntry("ia", 0, "Iowa", "Alisabeth Von Presley", "Wonder");
	addEntry("ks", 0, "Kansas", "Broderick Jones feat. Calio", "Tell Me");
	addEntry("ky", 0, "Kentucky", "Jordan Smith", "Sparrow");
	addEntry("la", 0, "Louisiana", "Brittany Pfantz", "Now You Do");
	addEntry("me", 0, "Maine", "King Kyote", "Get Out Alive");
	addEntry("md", 0, "Maryland", "Sisqó", "It's Up");
	addEntry("ma", 0, "Massachusetts", "Jared Lee", "Shameless");
	addEntry("mi", 0, "Michigan", "Ada LeAnn", "Natalie");
	addEntry("mn", 0, "Minnesota", "Yam Haus", "Ready to Go");
	addEntry("ms", 0, "Mississippi", "Keyone Starr", "Fire");
	addEntry("mo", 0, "Missouri", "Halie", "Better Things");
	addEntry("mt", 0, "Montana", "Jonah Prill", "Fire It Up");
	addEntry("ne", 0, "Nebraska", "Jocelyn", "Never Alone");
	addEntry("nv", 0, "Nevada", "The Crystal Method feat. Koda & VAAAL", "Watch Me Now");
	addEntry("nh", 0, "New Hampshire", "MARi", "Fly");
	addEntry("nj", 0, "New Jersey", "Brooke Alexx", "I Don't Take Pictures Anymore");
	addEntry("nm", 0, "New Mexico", "Khalisol", "Drop");
	addEntry("ny", 0, "New York", "Enisa", "Green Light");
	addEntry("nc", 0, "North Carolina", "John Morgan", "Right in the Middle");
	addEntry("nd", 0, "North Dakota", "Chloe Fredericks", "Can't Make You Love Me");
	addEntry("mp", 0, "Northern Marianas", "Sabyu", "Sunsets & Seaturtles");
	addEntry("oh", 0, "Ohio", "Macy Gray feat. The California Jet Club & Maino", "Every Night");
	addEntry("ok", 0, "Oklahoma", "AleXa", "Wonderland");
	addEntry("or", 0, "Oregon", "courtship.", "Million Dollar Smoothies");
	addEntry("pa", 0, "Pennsylvania", "Bri Steves", "Plenty Love");
	addEntry("pr", 0, "Puerto Rico", "Christian Pagán", "Loko");
	addEntry("ri", 0, "Rhode Island", "Hueston", "Held On Too Long");
	addEntry("sc", 0, "South Carolina", "Jesse LeProtti", "Not Alone");
	addEntry("sd", 0, "South Dakota", "Judd Hoos", "Bad Girl");
	addEntry("tn", 0, "Tennessee", "Tyler Braden", "Seventeen");
	addEntry("tx", 0, "Texas", "Grant Knoche", "Mr. Independent");
	addEntry("vi", 0, "U.S. Virgin Islands", "Cruz Rock", "Celebrando");
	addEntry("ut", 0, "Utah", "Savannah Keyes", "Sad Girl");
	addEntry("vt", 0, "Vermont", "Josh Panda", "Rollercoaster");
	addEntry("va", 0, "Virginia", "Almira Zaky", "Over You");
	addEntry("wa", 0, "Washington", "Allen Stone", "A Bit of Both");
	addEntry("dc", 0, "Washington D.C.", "NËITHER", "I Like It");
	addEntry("wv", 0, "West Virginia", "Alexis Cunningham", "Working on a Miracle");
	addEntry("wi", 0, "Wisconsin", "Jake'O", "Feel Your Love");
	addEntry("wy", 0, "Wyoming", "Ryan Charles", "New Boot Goofin'");
}