window.defineEntries = function (addEntry) {
	yr = 2021;
	addEntry("al", 2, "Albania", "Anxhela Peristeri", "Karma", "Karma");
	addEntry("au", 1, "Australia", "Montaigne", "Technicolour");
	addEntry("at", 2, "Austria", "Vincent Bueno", "Amen");
	addEntry("az", 1, "Azerbaijan", "Efendi", "Mata Hari");
	addEntry("be", 1, "Belgium", "Hooverphonic", "The Wrong Place");
	addEntry("bg", 2, "Bulgaria", "Victoria", "Growing Up Is Getting Old");
	addEntry("hr", 1, "Croatia", "Albina", "Tick-Tock");
	addEntry("cy", 1, "Cyprus", "Elena Tsagrinou", "El diablo", "The devil");
	addEntry("cz", 2, "Czech Republic", "Benny Cristo", "Omaga");
	addEntry("dk", 2, "Denmark", "Fyr og Flamme", "Øve os på hinanden", "Practice on each other");
	addEntry("ee", 2, "Estonia", "Uku Suviste", "The Lucky One");
	addEntry("fi", 2, "Finland", "Blind Channel", "Dark Side");
	addEntry("fr", 0, "France", "Barbara Pravi", "Voilà", "Behold");
	addEntry("ge", 2, "Georgia", "Tornike Kipiani", "You");
	addEntry("de", 0, "Germany", "Jendrik", "I Don't Feel Hate");
	addEntry("gr", 2, "Greece", "Stefania", "Last Dance");
	addEntry("is", 2, "Iceland", "Daði og Gagnamagnið", "10 Years");
	addEntry("ie", 1, "Ireland", "Lesley Roy", "Maps");
	addEntry("il", 1, "Israel", "Eden Alene", "Set Me Free");
	addEntry("it", 0, "Italy", "Måneskin", "Zitti e buoni", "Quiet and compliant");
	addEntry("lv", 2, "Latvia", "Samanta Tīna", "The Moon Is Rising");
	addEntry("lt", 1, "Lithuania", "The Roop", "Discoteque");
	addEntry("mt", 1, "Malta", "Destiny", "Je me casse", "I'm out of here");
	addEntry("md", 2, "Moldova", "Natalia Gordienko", "Sugar");
	addEntry("nl", 0, "Netherlands", "Jeangu Macrooy", "Birth of a New Age");
	addEntry("mk", 1, "North Macedonia", "Vasil", "Here I Stand");
	addEntry("no", 1, "Norway", "TIX", "Fallen Angel");
	addEntry("pl", 2, "Poland", "Rafał", "The Ride");
	addEntry("pt", 2, "Portugal", "The Black Mamba", "Love Is on My Side");
	addEntry("ro", 1, "Romania", "Roxen", "Amnesia");
	addEntry("ru", 1, "Russia", "Manizha", "Russian Woman");
	addEntry("sm", 2, "San Marino", "Senhit feat. Flo Rida", "Adrenalina", "Adrenaline");
	addEntry("rs", 2, "Serbia", "Hurricane", "Loco Loco", "Crazy, crazy");
	addEntry("si", 1, "Slovenia", "Ana Soklič", "Amen");
	addEntry("es", 0, "Spain", "Blas Cantó", "Voy a quedarme", "I will remain");
	addEntry("se", 1, "Sweden", "Tusse", "Voices");
	addEntry("ch", 2, "Switzerland", "Gjon's Tears", "Tout l'univers", "The entire universe");
	addEntry("ua", 1, "Ukraine", "Go_A", "Shum", "\"Шум\"; Noise");
	addEntry("gb", 0, "United Kingdom", "James Newman", "Embers");
}