window.defineEntries = function (addEntry) {
	yr = "2018";
	codeset = "eu";
	addEntry("al", -1, "Albania", "Eugent Bushpepa", "Mall", "Longing");
	addEntry("am", 1, "Armenia", "Sevak Khanagyan", "Qami", "\"Քամի\"; Wind");
	addEntry("au", -2, "Australia", "Jessica Mauboy", "We Got Love");
	addEntry("at", -1, "Austria", "Cesár Sampson", "Nobody but You");
	addEntry("az", 1, "Azerbaijan", "AISEL", "X My Heart");
	addEntry("by", 1, "Belarus", "ALEKSEEV", "Forever");
	addEntry("be", 1, "Belgium", "SENNEK", "A Matter of Time");
	addEntry("bg", -1, "Bulgaria", "Equinox", "Bones");
	addEntry("hr", 1, "Croatia", "Franka", "Crazy");
	addEntry("cy", -1, "Cyprus", "Eleni Foureira", "Fuego");
	addEntry("cz", -1, "Czech Republic", "Mikolas Josef", "Lie to Me");
	addEntry("dk", -2, "Denmark", "Rasmussen", "Higher Ground");
	addEntry("ee", -1, "Estonia", "Elina Nechayeva", "La forza");
	addEntry("fi", -1, "Finland", "Saara Aalto", "Monsters");
	addEntry("fr", 0, "France", "Madame Monsieur", "Mercy");
	addEntry("ge", 2, "Georgia", "Ethno-Jazz Band Iriao", "For You");
	addEntry("de", 0, "Germany", "Michael Schulte", "You Let Me Walk Alone");
	addEntry("gr", 1, "Greece", "Yianna Terzi", "Oniro mou", "\"Όνειρό μου\"; My dream");
	addEntry("hu", -2, "Hungary", "AWS", "Viszlát nyár", "Goodbye, summer");
	addEntry("is", 1, "Iceland", "Ari Ólafsson", "Our Choice");
	addEntry("ie", -1, "Ireland", "Ryan O'Shaughnessy", "Together");
	addEntry("il", -1, "Israel", "Netta", "Toy");
	addEntry("it", 0, "Italy", "Ermal Meta & Fabrizio Moro", "Non mi avete fatto niente", "You haven't done anything to me");
	addEntry("lv", 2, "Latvia", "Laura Rizzotto", "Funny Girl");
	addEntry("lt", -1, "Lithuania", "Ieva Zasimauskaitė", "When We're Old");
	addEntry("mk", 1, "F.Y.R. Macedonia", "Eye Cue", "Lost and Found");
	addEntry("mt", 2, "Malta", "Christabelle", "Taboo");
	addEntry("md", -2, "Moldova", "DoReDoS", "My Lucky Day");
	addEntry("me", 2, "Montenegro", "Vanja Radovanović", "Inje", "Hoarfrost");
	addEntry("nl", -2, "Netherlands", "Waylon", "Outlaw in 'Em");
	addEntry("no", -2, "Norway", "Alexander Rybak", "That's How You Write a Song");
	addEntry("pl", 2, "Poland", "Gromee feat. Lukas Meijer", "Light Me Up");
	addEntry("pt", 0, "Portugal", "Cláudia Pascoal", "O jardim", "The garden");
	addEntry("ro", 2, "Romania", "The Humans", "Goodbye");
	addEntry("ru", 2, "Russia", "Julia Samoylova", "I Won't Break");
	addEntry("sm", 2, "San Marino", "Jessika feat. Jenifer Brening", "Who We Are");
	addEntry("rs", -2, "Serbia", "Sanja Ilić & Balkanika", "Nova deca", "\"Нова деца\"; New children");
	addEntry("si", -2, "Slovenia", "Lea Sirk", "Hvala, ne!", "No, thanks!");
	addEntry("es", 0, "Spain", "Amaia & Alfred", "Tu canción", "Your song");
	addEntry("se", -2, "Sweden", "Benjamin Ingrosso", "Dance You Off");
	addEntry("ch", 1, "Switzerland", "ZiBBZ", "Stones");
	addEntry("ua", -2, "Ukraine", "MÉLOVIN", "Under the Ladder");
	addEntry("gb", 0, "United Kingdom", "SuRie", "Storm");
}