window.defineEntries = function (addEntry) {
	yr = 2020;
	addEntry("al", 2, "Albania", "Arilena Ara", "Fall from the Sky");
	addEntry("am", 2, "Armenia", "Athena Manoukian", "Chains on You");
	addEntry("au", 1, "Australia", "Montaigne", "Don't Break Me");
	addEntry("at", 2, "Austria", "Vincent Bueno", "Alive");
	addEntry("az", 1, "Azerbaijan", "Efendi", "Cleopatra");
	addEntry("by", 1, "Belarus", "VAL", "Da vidna", "\"Да відна\"; Before dawn");
	addEntry("be", 1, "Belgium", "Hooverphonic", "Release Me");
	addEntry("bg", 2, "Bulgaria", "Victoria", "Tears Getting Sober");
	addEntry("hr", 1, "Croatia", "Damir Kedžo", "Divlji vjetre", "Wild wind");
	addEntry("cy", 1, "Cyprus", "Sandro", "Running");
	addEntry("cz", 2, "Czech Republic", "Benny Cristo", "Kemama", "OK, mama");
	addEntry("dk", 2, "Denmark", "Ben & Tan", "Yes");
	addEntry("ee", 2, "Estonia", "Uku Suviste", "What Love Is");
	addEntry("fi", 2, "Finland", "Aksel", "Looking Back");
	addEntry("fr", 0, "France", "Tom Leeb", "Mon alliée (The Best in Me)", "My ally");
	addEntry("ge", 2, "Georgia", "Tornike Kipiani", "Take Me as I Am");
	addEntry("de", 0, "Germany", "Ben Dolic", "Violent Thing");
	addEntry("gr", 2, "Greece", "Stefania", "SUPERG!RL");
	addEntry("is", 2, "Iceland", "Daði & Gagnamagnið", "Think About Things");
	addEntry("ie", 1, "Ireland", "Lesley Roy", "Story of My Life");
	addEntry("il", 1, "Israel", "Eden Alene", "Feker libi", "\"ፍቅር ליבי\"; My beloved");
	addEntry("it", 0, "Italy", "Diodato", "Fai rumore", "You make noise");
	addEntry("lv", 2, "Latvia", "Samanta Tīna", "Still Breathing");
	addEntry("lt", 1, "Lithuania", "The Roop", "On Fire");
	addEntry("mt", 1, "Malta", "Destiny", "All of My Love");
	addEntry("md", 2, "Moldova", "Natalia Gordienko", "Prison");
	addEntry("nl", 0, "Netherlands", "Jeangu Macrooy", "Grow");
	addEntry("mk", 1, "North Macedonia", "Vasil", "You");
	addEntry("no", 1, "Norway", "Ulrikke", "Attention");
	addEntry("pl", 2, "Poland", "Alicja", "Empires");
	addEntry("pt", 2, "Portugal", "Elisa", "Medo de sentir", "Fear of feeling");
	addEntry("ro", 1, "Romania", "Roxen", "Alcohol You");
	addEntry("ru", 1, "Russia", "Little Big", "Uno", "One");
	addEntry("sm", 2, "San Marino", "Senhit", "Freaky!");
	addEntry("rs", 2, "Serbia", "Hurricane", "Hasta la vista", "See you later");
	addEntry("si", 1, "Slovenia", "Ana Soklič", "Voda", "Water");
	addEntry("es", 0, "Spain", "Blas Cantó", "Universo", "Universe");
	addEntry("se", 1, "Sweden", "The Mamas", "Move");
	addEntry("ch", 2, "Switzerland", "Gjon's Tears", "Répondez-moi", "Answer me");
	addEntry("ua", 1, "Ukraine", "Go_A", "Solovey", "\"Соловей\"; Nightingale");
	addEntry("gb", 0, "United Kingdom", "James Newman", "My Last Breath");
}