window.defineEntries = function (addEntry) {
	yr = "2022";
	codeset = "eu";
	addEntry("al", 1, "Albania", "Ronela Hajati", "Sekret", "Secret");
	addEntry("am", 1, "Armenia", "Rosa Linn", "Snap");
	addEntry("au", 2, "Australia", "Sheldon Riley", "Not the Same");
	addEntry("at", 1, "Austria", "LUM!X feat. Pia Maria", "Halo");
	addEntry("az", 2, "Azerbaijan", "Nadir Rüstəmli", "Fade to Black");
	addEntry("be", 2, "Belgium", "Jérémie Makiese", "Miss You");
	addEntry("bg", 1, "Bulgaria", "Intelligent Music Project", "Intention");
	addEntry("hr", 1, "Croatia", "Mia Dimšić", "Guilty Pleasure");
	addEntry("cy", 2, "Cyprus", "Andromache", "Ela", "\"Έλα\"; Come on");
	addEntry("cz", 2, "Czech Republic", "We Are Domi", "Lights Off");
	addEntry("dk", 1, "Denmark", "Reddi", "The Show");
	addEntry("ee", 2, "Estonia", "Stefan", "Hope");
	addEntry("fi", 2, "Finland", "The Rasmus", "Jezebel");
	addEntry("fr", 0, "France", "Alvan & Ahez", "Fulenn");
	addEntry("ge", 2, "Georgia", "Circus Mircus", "Lock Me In");
	addEntry("de", 0, "Germany", "Malik Harris", "Rockstars");
	addEntry("gr", 1, "Greece", "Amanda Georgiadi Tenfjord", "Die Together");
	addEntry("is", 1, "Iceland", "Systur", "Með hækkandi sól", "With the rising sun");
	addEntry("ie", 2, "Ireland", "Brooke", "That's Rich");
	addEntry("il", 2, "Israel", "Michael Ben David", "I.M");
	addEntry("it", 0, "Italy", "Mahmood & Blanco", "Brividi", "Shivers");
	addEntry("lv", 1, "Latvia", "Citi Zēni", "Eat Your Salad");
	addEntry("lt", 1, "Lithuania", "Monika Liu", "Sentimentai", "Feelings");
	addEntry("mt", 2, "Malta", "Emma Muscat", "I Am What I Am");
	addEntry("md", 1, "Moldova", "Zdob și Zdub & Frații Advahov", "Trenulețul", "The little train");
	addEntry("me", 2, "Montenegro", "Vladana", "Breathe");
	addEntry("nl", 1, "Netherlands", "S10", "De diepte");
	addEntry("mk", 2, "North Macedonia", "Andrea", "Circles");
	addEntry("no", 1, "Norway", "Subwoolfer", "Give That Wolf a Banana");
	addEntry("pl", 2, "Poland", "Ochman", "River");
	addEntry("pt", 1, "Portugal", "Maro", "Saudade, saudade", "Longing, longing");
	addEntry("ro", 2, "Romania", "WRS", "Llámame", "Call me");
	addEntry("sm", 2, "San Marino", "Achille Lauro", "Stripper");
	addEntry("rs", 2, "Serbia", "Konstrakta", "In corpore sano", "In a healthy body");
	addEntry("si", 1, "Slovenia", "LPS", "Disko", "Disco");
	addEntry("es", 0, "Spain", "Chanel", "SloMo");
	addEntry("se", 2, "Sweden", "Cornelia Jakobs", "Hold Me Closer");
	addEntry("ch", 1, "Switzerland", "Marius Bear", "Boys Do Cry");
	addEntry("ua", 1, "Ukraine", "Kalush Orchestra", "Stefania", "\"Стефанія\"");
	addEntry("gb", 0, "United Kingdom", "Sam Ryder", "Space Man");
}