window.defineEntries = function (addEntry) {
	yr = "2021f";
	codeset = "eu";
	addEntry("al", 1, "Albania", "Anxhela Peristeri", "Karma", "Karma");
	addEntry("be", 1, "Belgium", "Hooverphonic", "The Wrong Place");
	addEntry("cy", 1, "Cyprus", "Elena Tsagrinou", "El diablo", "The devil");
	addEntry("gr", 1, "Greece", "Stefania", "Last Dance");
	addEntry("is", 1, "Iceland", "Daði og Gagnamagnið", "10 Years");
	addEntry("il", 1, "Israel", "Eden Alene", "Set Me Free");
	addEntry("mt", 1, "Malta", "Destiny", "Je me casse", "I'm out of here");
	addEntry("pt", 1, "Portugal", "The Black Mamba", "Love Is on My Side");
	addEntry("ru", 1, "Russia", "Manizha", "Russian Woman");
	addEntry("rs", 1, "Serbia", "Hurricane", "Loco Loco", "Crazy, crazy");
	addEntry("es", 1, "Spain", "Blas Cantó", "Voy a quedarme", "I will remain");
	addEntry("ch", 1, "Switzerland", "Gjon's Tears", "Tout l'univers", "The entire universe");
	addEntry("gb", 1, "United Kingdom", "James Newman", "Embers");
	addEntry("az", 2, "Azerbaijan", "Efendi", "Mata Hari");
	addEntry("bg", 2, "Bulgaria", "Victoria", "Growing Up Is Getting Old");
	addEntry("fi", 2, "Finland", "Blind Channel", "Dark Side");
	addEntry("fr", 2, "France", "Barbara Pravi", "Voilà", "Behold");
	addEntry("de", 2, "Germany", "Jendrik", "I Don't Feel Hate");
	addEntry("it", 2, "Italy", "Måneskin", "Zitti e buoni", "Quiet and compliant");
	addEntry("lt", 2, "Lithuania", "The Roop", "Discoteque");
	addEntry("md", 2, "Moldova", "Natalia Gordienko", "Sugar");
	addEntry("no", 2, "Norway", "TIX", "Fallen Angel");
	addEntry("sm", 2, "San Marino", "Senhit feat. Flo Rida", "Adrenalina", "Adrenaline");
	addEntry("se", 2, "Sweden", "Tusse", "Voices");
	addEntry("ua", 2, "Ukraine", "Go_A", "Shum", "\"Шум\"; Noise");
	addEntry("nl", -23, "Netherlands", "Jeangu Macrooy", "Birth of a New Age");
}